### ISSUE TITLE
[Question] Undefined method for Swiflint four issues - during Jenkins Build

### ISSUE THREAD

**Issue by Drwalcore** [ashfurrow/danger-ruby-swiftlint#119]
Hello, first of all, I'd like to thank the maintainer of this repository for writing this tool!

I am encountering this error during Swiftlint phase on my Jenkins Pipeline job and I cannot determine what could be the problem. Same Dangerfile worked really smooth in another project with same gems, dependencies but with another CI (Travis).

```
+ bundle exec danger
/Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-swiftlint-0.12.1/lib/danger_plugin.rb:106:in `lint_files': [31m (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined method `+@' for "### SwiftLint found issues\n\n":String[0m
 #  from Dangerfile:42
 #  -------------------------------------------
 #  swiftlint.directory = app_path
 >  swiftlint.lint_files(app_files, inline_mode: false)
 #  
 #  -------------------------------------------
	from Dangerfile:42:in `eval_file'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/danger_core/executor.rb:28:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/lib/danger/commands/runner.rb:70:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/gems/danger-5.11.1/bin/danger:5:in `<top (required)>'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/danger:23:in `load'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/danger:23:in `<main>'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mobile/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[!] The exception involves the following plugins:
 -  danger-swiftlint
```

My Swiftlint related lines are as follows in *Dangerfile*

```
app_path = File.join(BASE_PATH, APP_DIR)
test_path = File.join(BASE_PATH, TESTS_DIR)
files = (git.added_files + git.modified_files).map { |path| File.join(BASE_PATH, path) }
app_files = files.select { |path| path.start_with?(app_path + '/') }
test_files = files.select { |path| path.start_with?(test_path + '/') }

swiftlint.directory = app_path
swiftlint.lint_files(app_files, inline_mode: false)

swiftlint.directory = test_path
swiftlint.lint_files(test_files, inline_mode: false)
```

EDIT:
When I enter on my Jenkins Mac Mini and run `danger pr` it works, but it does not show half of the reports. Looks like it reports only Swiftlint for `app_path`. Still, Jenkins fails whole Danger process.

If You have any questions, please ask, I will answer them when possible. Suggestions welcome! Thank you again!
Michael.

**Comment by ashfurrow** [comment]
Good morning! Sorry to hear you're having trouble – thanks for the detailed issue!

When I see different behaviour in different environments, the first thing I check is the Ruby version. It looks like the crash is using 2.2.3, check what Travis is using successfully. (The other thing I'd recommend is updating to a newer version of this library. It looks like you're on 0.12.1, which is [over a year old](https://github.com/ashfurrow/danger-ruby-swiftlint/releases/tag/0.12.1)! But that's not the cause of the problem here.)

I took a look and the problem appears to be [this line of code](https://github.com/ashfurrow/danger-ruby-swiftlint/blob/d5afc5b69faa8155b7851ccf1ca6a797e18cf5d0/lib/danger_plugin.rb#L106) (that's the version you're using, but the [same line](https://github.com/ashfurrow/danger-ruby-swiftlint/blob/3ddb67be2e3cd4411a514aec3dfe260654bd3d3b/lib/danger_plugin.rb#L113) is on `master`). Ruby is interpreting this as a unary plus operator, which doesn't exist on the string class.

It looks like a copy/paste error, removing the `+` from in front of the string should fix the problem. Would you have time to submit a pull request? Thanks again!

**Comment by Drwalcore** [comment]
Good evening, first of all - thank You for looking at my issue.

I will be more than happy to try to submit an Pull Request, I will do my best and of course follow given hints!

With regards,
Michael

**Comment by ashfurrow** [comment]
Glad to hear it! It should be a single-line change but if you want some help, let me know and we chan schedule a screen-share to pair on it.

**Comment by Drwalcore** [comment]
I think I've managed, here's my check list :)
- [x] Remove unary plus operator and push changes to fork
- [ ] Open PR with my changes
- [ ] Update my local CI with newest version
- [ ] Run my `Dangerfile` fork on my problematic CI
- [ ] Write test? Is that needed?

**Comment by ashfurrow** [comment]
Looks good! No need for tests in this case. I'll review the PR now.

**Comment by Drwalcore** [comment]
I see that some tests are failing at the moment. I ran `bundle exec rake` locally and the same tests failed.
