### ISSUE TITLE
Latest visible release version is not lates tagged version

### ISSUE THREAD

**Issue by apps4everyone** [ashfurrow/danger-ruby-swiftlint#167]
Latest visible release version (0.24.5) is not lates tagged version (0.26.0).

<img width="814" alt="Screenshot 2021-08-20 at 09 12 15" src="https://user-images.githubusercontent.com/1915802/130194787-e3b14845-3e8c-404f-beb3-d8a5c8fd8aa7.png">

**Comment by ashfurrow** [comment]
The releases are tagged, [here](https://github.com/ashfurrow/danger-ruby-swiftlint/tags). That UI shows the GitHub releases, which are like tags but confusing and proprietary:

<img width="476" alt="Screen Shot 2021-08-23 at 4 36 19 PM" src="https://user-images.githubusercontent.com/498212/130508600-2b7c0e95-c235-4f2f-9738-f75526209ad2.png">

I think when thii made the release, they used the GitHub web UI instead of `git tag` (which is what I do). Let me know if this clears things up.

**Comment by apps4everyone** [comment]
only wanted to mention this because on the first view on hithub is not showing the latest tag but the release version. (the in the right on this image):

<img width="1440" alt="Screenshot 2021-08-23 at 21 59 49" src="https://user-images.githubusercontent.com/1915802/130511552-6a709516-d844-48e8-84ea-2c5c676eac92.png">

**Comment by ashfurrow** [comment]
Ugh, why does GitHub make this so frustrating.
